// Graph API のバージョン指定 v1.0 or beta
@graph_endpoint = https://graph.microsoft.com/beta

###
//エージェント ID ブループリントプリンシパルの一覧を取得
GET {{graph_endpoint}}/servicePrincipals/microsoft.graph.agentIdentityBlueprintPrincipal
Content-type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}
###

###
//エージェント ID ブループリントプリンシパルを作成する
@agentBlueprintAppId1=86f8f4ca-8e3d-4fd5-a0ab-fcd4f812f5d7
POST {{graph_endpoint}}/servicePrincipals/microsoft.graph.agentIdentityBlueprintPrincipal
Content-type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}

{
  "appId": "{{agentBlueprintAppId1}}"
}
###