// Graph API のバージョン指定 v1.0 or beta
@graph_endpoint = https://graph.microsoft.com/v1.0

//claimsMappingPolicy
//https://learn.microsoft.com/en-us/graph/api/resources/claimsmappingpolicy?view=graph-rest-1.0
###
// claimsMappingPolicies の一覧を取得
GET {{graph_endpoint}}/policies/claimsMappingPolicies
Authorization: Bearer {{$aadV2Token appOnly}}
###

###
// claimsMappingPolicies のオブジェクト ID を指定して特定のポリシーを取得
@claimsMappingPolicyId1 = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
GET {{graph_endpoint}}/policies/claimsMappingPolicies/{{claimsMappingPolicyId1}}
Authorization: Bearer {{$aadV2Token appOnly}}
###

###
// claimsMappingPolicies の作成
POST {{graph_endpoint}}/policies/claimsMappingPolicies
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}

{
    "displayName": "Test1234",
    "definition": [
        "{
            \"ClaimsMappingPolicy\":
                {
                    \"Version\":1,
                    \"IncludeBasicClaimSet\":\"true\",
                    \"ClaimsSchema\": 
                        [  
                            {
                                \"Source\":\"user\",
                                \"ID\":\"employeeid\",
                                \"SamlClaimType\":\"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/employeeid\",
                                \"JwtClaimType\":\"employeeid\"
                            },
                            {
                                \"Source\":\"company\",
                                \"ID\":\"tenantcountry\",
                                \"SamlClaimType\":\"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/country\",
                                \"JwtClaimType\":\"country\"
                            },
                            {
                                \"Source\":\"user\",
                                \"ID\":\"accountEnabled\",
                                \"SamlClaimType\":\"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/accountEnabled\",
                                \"JwtClaimType\":\"accountEnabled\"
                            }
                        ]
                }
        }"
    ]
}
###

###
// claimsMappingPolicies の更新
//MemberOf で特定のグループに所属しているユーザーの場合にだけクレームを付与することができる
@claimsMappingPolicyId2 = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

PATCH {{graph_endpoint}}/policies/claimsMappingPolicies/{{claimsMappingPolicyId2}}
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}

{
    "displayName": "Test1234",
    "definition": [
        "{
            \"ClaimsMappingPolicy\":
                {
                    \"Version\":1,
                    \"IncludeBasicClaimSet\":\"true\",
                    \"ClaimsSchema\": 
                        [  
                            {
                                \"Source\":\"user\",
                                \"ID\":\"employeeid\",
                                \"SamlClaimType\":\"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/employeeid\",
                                \"JwtClaimType\":\"employeeid\"
                            },
                            {
                                \"Source\":\"company\",
                                \"ID\":\"tenantcountry\",
                                \"SamlClaimType\":\"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/country\",
                                \"JwtClaimType\":\"country\"
                            },
                            {
                                \"Source\":\"user\",
                                \"ID\":\"accountEnabled\",
                                \"SamlClaimType\":\"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/accountEnabled\",
                                \"JwtClaimType\":\"accountEnabled\",
                                \"MemberOf\":[\"oid:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\"]
                            }
                        ]
                }
        }"
    ]
}
###

###
// claimsMappingPolicies の削除
@claimsMappingPolicyId3 = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

DELETE {{graph_endpoint}}/policies/claimsMappingPolicies/{{claimsMappingPolicyId3}}
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}
###

###
// claimsMappingPolicies の割り当て一覧
//https://learn.microsoft.com/en-us/graph/api/serviceprincipal-list-claimsmappingpolicies?view=graph-rest-1.0&tabs=http
@servicePrincipalsObjectId1= xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
GET {{graph_endpoint}}/servicePrincipals/{{servicePrincipalsObjectId1}}/claimsMappingPolicies/$ref
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}
###

###
// サービスプリンシパルに claimsMappingPolicies を割り当てる
//https://learn.microsoft.com/en-us/graph/api/serviceprincipal-post-claimsmappingpolicies?view=graph-rest-1.0&tabs=http
@servicePrincipalsObjectId2= xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
@claimsMappingPolicyId4 = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

POST {{graph_endpoint}}/servicePrincipals/{{servicePrincipalsObjectId2}}/claimsMappingPolicies/$ref
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}

{
"@odata.id":"https://graph.microsoft.com/v1.0/policies/claimsMappingPolicies/{{claimsMappingPolicyId4}}"
}
###

###
// サービスプリンシパルに 割り当てた claimsMappingPolicies を解除する
//https://learn.microsoft.com/en-us/graph/api/serviceprincipal-delete-claimsmappingpolicies?view=graph-rest-1.0&tabs=http
@servicePrincipalsObjectId3=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
@claimsMappingPolicyId5 = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
DELETE {{graph_endpoint}}/servicePrincipals/{{servicePrincipalsObjectId3}}/claimsMappingPolicies/{{claimsMappingPolicyId5}}/$ref
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}
###

###
// アクセストークンの有効期限のポリシー作成
POST {{graph_endpoint}}/policies/tokenLifetimePolicies
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}

{
    "definition": [
        "{\"TokenLifetimePolicy\":{\"Version\":1,\"AccessTokenLifetime\":\"8:00:00\"}}"
    ],
    "displayName": "Contoso token lifetime policy",
    "isOrganizationDefault": false
}
###

###
// アクセストークンの有効期限のポリシー一覧取得
GET {{graph_endpoint}}/policies/tokenLifetimePolicies
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}
###

###
// アクセストークンの有効期限のポリシーの取得
@tokenLifetimePolicyId1 = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
GET {{graph_endpoint}}/policies/tokenLifetimePolicies/{{tokenLifetimePolicyId1}}
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}
###

###
// アクセストークンの有効期限のポリシーの更新
@tokenLifetimePolicyId2 = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
PATCH {{graph_endpoint}}/policies/tokenLifetimePolicies/{{tokenLifetimePolicyId2}}
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}

{
    "definition": [
        "{\"TokenLifetimePolicy\":{\"Version\":1,\"AccessTokenLifetime\":\"8:00:00\"}}"
    ],
    "displayName": "Contoso token lifetime policy",
    "isOrganizationDefault": false
}
###

###
// アクセストークンの有効期限のポリシーの削除
@tokenLifetimePolicyId3 = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
DELETE {{graph_endpoint}}/policies/tokenLifetimePolicies/{{tokenLifetimePolicyId3}}
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}
###

###
// アクセストークンの有効期限のポリシーをサービスプリンシパルに割り当てる
@tokenLifetimePolicyId4=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
@servicePrincipalsObjectId4=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
POST {{graph_endpoint}}/servicePrincipals/{{servicePrincipalsObjectId4}}/tokenLifetimePolicies/$ref
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}

{
  "@odata.id":"https://graph.microsoft.com/v1.0/policies/tokenLifetimePolicies/{{tokenLifetimePolicyId4}}"
}

###

###
// サービスプリンシパルに割り当てられたアクセストークンの有効期限のポリシーの一覧取得
@servicePrincipalsObjectId5=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
GET {{graph_endpoint}}/servicePrincipals/{{servicePrincipalsObjectId5}}/tokenLifetimePolicies
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}
###

###
// アクセストークンの有効期限のポリシーをサービスプリンシパルの割り当て削除
@tokenLifetimePolicyId4=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
@servicePrincipalsObjectId6=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
DELETE {{graph_endpoint}}/servicePrincipals/{{servicePrincipalsObjectId4}}/tokenLifetimePolicies/{{tokenLifetimePolicyId4}}/$ref
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}
###

###
// customClaimsPolicy の一覧取得
@servicePrincipalsObjectId7=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
GET {{graph_endpoint}}/servicePrincipals/{{servicePrincipalsObjectId7}}/claimsPolicy
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}
###

###
// customClaimsPolicy の更新
@servicePrincipalsObjectId8=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
PATCH  {{graph_endpoint}}/servicePrincipals/{{servicePrincipalsObjectId8}}/claimsPolicy
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}

{
  "claims": [
    {
      "@odata.type": "#microsoft.graph.samlNameIdClaim",
      "serviceProviderNameQualifier": null,
      "nameIdFormat": "emailAddress",
      "configurations": [
        {
          "condition": null,
          "attribute": {
            "@odata.type": "#microsoft.graph.sourcedAttribute",
            "id": "userprincipalname",
            "source": "user",
            "isExtensionAttribute": false
          },
          "transformations": []
        }
      ]
    },
    {
      "@odata.type": "#microsoft.graph.customClaim",
      "name": "givenname",
      "namespace": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims",
      "tokenFormat": [
        "saml",
        "jwt"
      ],
      "samlAttributeNameFormat": null,
      "configurations": [
        {
          "condition": null,
          "attribute": {
            "@odata.type": "#microsoft.graph.sourcedAttribute",
            "id": "givenname",
            "source": "user",
            "isExtensionAttribute": false
          },
          "transformations": []
        }
      ]
    },
    {
      "@odata.type": "#microsoft.graph.customClaim",
      "name": "surname",
      "namespace": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims",
      "tokenFormat": [
        "saml",
        "jwt"
      ],
      "samlAttributeNameFormat": null,
      "configurations": [
        {
          "condition": null,
          "attribute": {
            "@odata.type": "#microsoft.graph.sourcedAttribute",
            "id": "surname",
            "source": "user",
            "isExtensionAttribute": false
          },
          "transformations": []
        }
      ]
    },
    {
      "@odata.type": "#microsoft.graph.customClaim",
      "name": "emailaddress",
      "namespace": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims",
      "tokenFormat": [
        "saml",
        "jwt"
      ],
      "samlAttributeNameFormat": null,
      "configurations": [
        {
          "condition": null,
          "attribute": {
            "@odata.type": "#microsoft.graph.sourcedAttribute",
            "id": "mail",
            "source": "user",
            "isExtensionAttribute": false
          },
          "transformations": []
        }
      ]
    },
    {
      "@odata.type": "#microsoft.graph.customClaim",
      "name": "name",
      "namespace": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims",
      "tokenFormat": [
        "saml",
        "jwt"
      ],
      "samlAttributeNameFormat": null,
      "configurations": [
        {
          "condition": null,
          "attribute": {
            "@odata.type": "#microsoft.graph.sourcedAttribute",
            "id": "userprincipalname",
            "source": "user",
            "isExtensionAttribute": false
          },
          "transformations": []
        }
      ]
    },
    {
      "@odata.type": "#microsoft.graph.customClaim",
      "name": "appproxy_test",
      "namespace": null,
      "tokenFormat": [
        "saml",
        "jwt"
      ],
      "samlAttributeNameFormat": null,
      "configurations": [
        {
          "condition": null,
          "attribute": {
            "@odata.type": "#microsoft.graph.sourcedAttribute",
            "id": "accountenabled",
            "source": "user",
            "isExtensionAttribute": false
          },
          "transformations": []
        }
      ]
    },
        {
      "@odata.type": "#microsoft.graph.customClaim",
      "name": "appproxy_test3",
      "namespace": null,
      "tokenFormat": [
        "saml",
        "jwt"
      ],
      "samlAttributeNameFormat": null,
      "configurations": [
        {
          "condition": null,
          "attribute": {
            "@odata.type": "#microsoft.graph.sourcedAttribute",
            "id": "city",
            "source": "user",
            "isExtensionAttribute": false
          },
          "transformations": []
        }
      ]
    }
  ]
}
###

###
// claimsPolicy を作成または置換する
@servicePrincipalsObjectId9=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
PUT  {{graph_endpoint}}/servicePrincipals/{{servicePrincipalsObjectId9}}/claimsPolicy
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}

{
  "claims": [
        {
            "@odata.type": "#microsoft.graph.customClaim",
            "name": "appproxy_test3",
            "namespace": null,
            "tokenFormat": [
                "saml",
                "jwt"
            ],
            "samlAttributeNameFormat": null,
            "configurations": [
                {
                    "condition": null,
                    "attribute": {
                        "@odata.type": "#microsoft.graph.sourcedAttribute",
                        "id": "city",
                        "source": "user",
                        "isExtensionAttribute": false
                    },
                    "transformations": []
                }
            ]
        }
  ]
}
###


###
// authorizationPolicy の一覧を取得
GET  {{graph_endpoint}}/policies/authorizationPolicy
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}

###

###
// authorizationPolicy の更新
PATCH {{graph_endpoint}}/policies/authorizationPolicy
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}

{
  "blockMsolPowerShell": true,
}
###


###
// homeRealmDiscoveryPolicies を一覧表示する
GET {{graph_endpoint}}/policies/homeRealmDiscoveryPolicies
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}
###

###
// HomeRealmDiscoveryPolicy を取得する
@homeRealmDiscoveryPolicyId1 = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
GET {{graph_endpoint}}/policies/homeRealmDiscoveryPolicies/{{homeRealmDiscoveryPolicyId1}}
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}
###
###
// homerealmdiscoverypolicy 作成する
POST  {{graph_endpoint}}/policies/homeRealmDiscoveryPolicies
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}

{
  "definition": [
    "{\"HomeRealmDiscoveryPolicy\":{\"AllowCloudPasswordValidation\":true,\"AlternateIdLogin\":{\"Enabled\":true}}}"
  ],
  "displayName": "example1234",
  "isOrganizationDefault": false
}
###

###
// homerealmdiscoverypolicy を更新する
@homeRealmDiscoveryPolicyId3 = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
PATCH  {{graph_endpoint}}/policies/homeRealmDiscoveryPolicies/{{homeRealmDiscoveryPolicyId3}}
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}

{
  "definition": [
    "{\"HomeRealmDiscoveryPolicy\":{\"AllowCloudPasswordValidation\":true,\"AlternateIdLogin\":{\"Enabled\":true}}}"
  ],
  "displayName": "example1234",
  "isOrganizationDefault": true
}
###

###
// homerealmdiscoverypolicy を削除する
@homeRealmDiscoveryPolicyId4 = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
DELETE  {{graph_endpoint}}/policies/homeRealmDiscoveryPolicies/{{homeRealmDiscoveryPolicyId4}}
Authorization: Bearer {{$aadV2Token appOnly}}
###


###
//  permissionGrantPolicies の一覧を取得
GET {{graph_endpoint}}/policies/permissionGrantPolicies
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}
###

###
//  permissionGrantPolicies の microsoft-user-default-recommended を取得
GET {{graph_endpoint}}/policies/permissionGrantPolicies/microsoft-user-default-recommended
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}
###

###
//  permissionGrantPolicies を新しく作る
POST {{graph_endpoint}}/policies/permissionGrantPolicies
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}

{
  "id": "DemoConsent-DelegatedPermissions",
  "displayName": "DemoConsent-DelegatedPermissions",
  "description": "Grapn user consent to files.ReadWrite.All"
}

###

###
//  permissionGrantPolicies に include コレクションを追加する
@permissionGrantPolicyId1 = DemoConsent-DelegatedPermissions
POST {{graph_endpoint}}/policies/permissionGrantPolicies/{{permissionGrantPolicyId1}}/includes
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}

{
  "permissionType": "delegated",
}
###

###
//  カスタムロールを作成し、カスタムロールに permissionGrantPolicies をアサインする
POST {{graph_endpoint}}/roleManagement/directory/roleDefinitions
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}

{
    "description": "DemoConsent-DelegatedPermissions-CustomRole",
    "displayName": "DemoConsent-DelegatedPermissions-CustomRole",
    "isEnabled": true,
    "rolePermissions":
    [
        {
            "allowedResourceActions":
            [
                "microsoft.directory/servicePrincipals/managePermissionGrantsForSelf.DemoConsent-DelegatedPermissions"
            ]
        }
    ]
}
###

###
//同意のポリシーを削除する
@Id1=DemoConsent-DelegatedPermissions
DELETE  {{graph_endpoint}}/policies/permissionGrantPolicies/{{Id1}}
Content-Type: application/json
Authorization: Bearer {{$aadV2Token appOnly}}
###