// Graph API のバージョン指定 v1.0 or beta
@graph_endpoint = https://graph.microsoft.com/v1.0

###
// サービスプリンシパルの一覧を取得
GET {{graph_endpoint}}/servicePrincipals
Authorization: Bearer {{$aadV2Token appOnly}}
###

###
// サービスプリンシパルの数を取得
GET {{graph_endpoint}}/servicePrincipals
    ?$count=true
Authorization: Bearer {{$aadV2Token appOnly}}
ConsistencyLevel: eventual
###

###
// サービスプリンシパルのオブジェクトID を指定して情報を取得
@servicePrincipalId = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
GET {{graph_endpoint}}/servicePrincipals/{{servicePrincipalId}}
Authorization: Bearer {{$aadV2Token appOnly}}
###
