// Microsoft Entra ID のOBOフロー
// https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-on-behalf-of-flow

//各種設定
@App_client_id = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
@App_client_secret = client_secret of App
@WebAPI1_client_id = yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy
@WebAPI1_scope = scope of WebAPI1
@WebAPI1_client_secret = client_secret of WebAPI1
@WebAPI2_client_id = zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz
@WebAPI2_scope = scope of WebAPI1
###
// 認可リクエスト
// 右クリック > Genarate Code Snippet > Powershell >  Invoke-WebRequest
// をクリックし、-Uri　に設定されている URL をブラウザーで開いて認証する
GET {{baseUrl}}/{{tenantId_or_tenantName}}/oauth2/v2.0/authorize
    ?client_id={{App_client_id}}
    &response_type=code
    &redirect_uri=https://jwt.ms
    &response_mode=query
    &scope=openid {{WebAPI1_scope}}
    &state=12345
    &nonce=1234
###

###
// トークンリクエスト (App から WebAPI1 へのアクセスるためのトークンを取得)
// 認可リクエストにて Microsoft Entra ID の認証後にリダイレクトされたURL からクエリストリングの code の値を取得
# @name tokenRequest
@code = 認可リクエストで取得したcodeを入力
POST {{baseUrl}}/{{tenantId_or_tenantName}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{App_client_id}}
&scope={{WebAPI1_scope}}
&code={{code}}
&redirect_uri=https://jwt.ms
&grant_type=authorization_code
&client_secret={{App_client_secret}}
###

###
// 中間層アクセストークンリクエスト (WebAPI1から WebAPI2 へのアクセスるためのトークンを取得)
@accessToken = {{tokenRequest.response.body.$.access_token}}
POST {{baseUrl}}/{{tenantId_or_tenantName}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer
&client_id={{WebAPI1_client_id}}
&client_secret={{WebAPI1_client_secret}}
&assertion={{accessToken}}
&scope={{WebAPI2_scope}}
&requested_token_use=on_behalf_of
###

